"""Ray-level context-loop holonomy: Bargmann strand invariants and hardware plan.

Companion to contextuality-obstructions verification V12 (wf_loop_holonomy.py).
For a closed loop of measurement bases the gauge-invariant content at the
projective level is the per-eigenvector-strand Bargmann phase; the finer
tau-level (determinant-section) holonomy is exposed separately and is NOT
directly interferometric. numpy-only.
"""
from __future__ import annotations
import numpy as np

_H = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
_S = np.diag([1, 1j])

def mub_loop_bases() -> list[np.ndarray]:
    """The Z -> X -> Y qubit MUB loop generated by H and S (columns = eigenvectors)."""
    return [np.eye(2), _H.copy(), _S @ _H]

def bargmann_invariant(chain: list[np.ndarray]) -> complex:
    """Gauge-invariant phase of a closed chain of vectors."""
    p = 1 + 0j
    for a in range(len(chain)):
        p *= np.vdot(chain[a], chain[(a + 1) % len(chain)])
    if abs(p) < 1e-12:
        raise ValueError("chain contains an orthogonal step; invariant undefined")
    return p / abs(p)

def strand_phases(bases: list[np.ndarray] | None = None) -> tuple[float, float, complex]:
    """(phase_strand0, phase_strand1, loop_product) for a closed basis loop."""
    B = mub_loop_bases() if bases is None else bases
    s0 = bargmann_invariant([V[:, 0] for V in B])
    s1 = bargmann_invariant([V[:, 1] for V in B])
    return float(np.angle(s0)), float(np.angle(s1)), s0 * s1

def det_section_holonomy(loop_unitaries: list[np.ndarray], closer: np.ndarray) -> complex:
    """tau-level invariant: det of the SU-closed loop composite (V12). Section-dependent
    up to mu_n in general; its square is section-independent for n=2."""
    L = closer.copy()
    for U in reversed(loop_unitaries):
        L = L @ U
    return complex(np.linalg.det(L))

def hadamard_test_plan(bases: list[np.ndarray] | None = None) -> list[dict]:
    """Measurement plan reconstructing every strand phase from single-qubit
    Hadamard tests: entries {strand, step, part, prep, unitary}; the overlap
    <a_k|b_k> = <k| Va^dag Vb |k> (forward orientation, matching
    bargmann_invariant) is Re/Im-read on the ancilla."""
    B = mub_loop_bases() if bases is None else bases
    n = len(B)
    plan = []
    for k in (0, 1):
        for a in range(n):
            b = (a + 1) % n
            U = B[a].conj().T @ B[b]
            for part in ("re", "im"):
                plan.append({"strand": k, "step": a, "part": part,
                             "prep": k, "unitary": U})
    return plan
