from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .metadata import COORDINATE_CONVENTION, CRITERION, INTEGER_CARRY_RULE, QKERNEL_VERSION
from .sat_export import build_dimacs_cnf
from .ir import WeylProgram


@dataclass(frozen=True)
class WcnfModel:
    """Weighted CNF model for external MaxSAT solvers.

    Hard clauses encode odd-Q feasibility:

        A^T lambda = 0 mod 2
        b^T lambda = 1 mod 2

    Soft clauses minimize selected contexts:

        weight 1: -lambda_i

    An assignment that satisfies all hard clauses and minimizes violated soft
    clauses minimizes the Hamming weight of lambda.
    """

    hard_clauses: list[list[int]]
    soft_clauses: list[tuple[int, list[int]]]
    num_vars: int
    top_weight: int
    comments: list[str]
    lambda_vars: list[int]

    def to_wcnf(self) -> str:
        lines: list[str] = []
        for comment in self.comments:
            lines.append(f"c {comment}")
        lines.append(
            f"p wcnf {self.num_vars} {len(self.hard_clauses) + len(self.soft_clauses)} {self.top_weight}"
        )
        for clause in self.hard_clauses:
            lines.append(f"{self.top_weight} " + " ".join(str(lit) for lit in clause) + " 0")
        for weight, clause in self.soft_clauses:
            lines.append(f"{weight} " + " ".join(str(lit) for lit in clause) + " 0")
        return "\n".join(lines) + "\n"


def build_wcnf_maxsat(program: WeylProgram) -> WcnfModel:
    """Build a WCNF MaxSAT model for minimum odd-Q kernel search.

    Hard clauses are generated by the SAT export without a max-weight bound.
    Soft clauses are `(-lambda_i)` with unit weight. Violating such a clause
    means selecting context i. Therefore minimizing total soft-violation cost
    minimizes |lambda|.
    """
    dimacs = build_dimacs_cnf(program, max_weight=None)

    lambda_vars = dimacs.lambda_vars
    soft = [(1, [-var]) for var in lambda_vars]
    top = len(lambda_vars) + 1

    comments = [
        "qkernel_wcnf_v1",
        f"qkernel_version {QKERNEL_VERSION}",
        f"criterion {CRITERION['id']}",
        f"coordinate_convention {COORDINATE_CONVENTION['id']}",
        f"integer_carry_rule {INTEGER_CARRY_RULE['id']}",
        "hard clauses encode A^T lambda = 0 and b^T lambda = 1",
        "soft clauses -lambda_i minimize selected contexts",
    ]
    comments.extend(dimacs.comments)

    return WcnfModel(
        hard_clauses=dimacs.clauses,
        soft_clauses=soft,
        num_vars=dimacs.num_vars,
        top_weight=top,
        comments=comments,
        lambda_vars=lambda_vars,
    )


def write_wcnf_maxsat(program: WeylProgram, path: str | Path) -> WcnfModel:
    model = build_wcnf_maxsat(program)
    Path(path).write_text(model.to_wcnf(), encoding="utf-8")
    return model
